name: Ingestion of Fractal Visions Transaction Data on Soneium

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  soneium-data-ingestion:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Add timeout to prevent hanging jobs
    permissions:
      contents: write  # Add write permissions for the GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'  # Enable pip caching

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set up environment variables
        run: |
          echo "DUNE_API_KEY_FRACTALVISIONS_SONEIUM=${{ secrets.DUNE_API_KEY_FRACTALVISIONS_SONEIUM }}" >> .env
          echo "DUNE_QUERY_SONEIUM_CHECKPOINT=${{ secrets.DUNE_QUERY_SONEIUM_CHECKPOINT }}" >> .env
          echo "DUNE_API_REQUEST_TIMEOUT=${{ secrets.DUNE_API_REQUEST_TIMEOUT }}" >> .env
          
      - name: Run job ingest pipeline
        run: python ingest.py
        continue-on-error: false  # Stop workflow if script fails 